import { NextResponse } from 'next/server'
import { readFile } from 'fs/promises'
import { join } from 'path'
import { supabaseAdmin } from '@/lib/supabase'
import { getTokenBalance } from '@/lib/solana'
import { PLOT_TIERS, ANIMALS } from '@/config/game'
import type { PlotTier } from '@/config/game'
import { logEvent } from '@/lib/logEvent'
import { checkAchievements } from '@/lib/checkAchievements'

export async function POST(req: Request) {
  const { plotId, wallet } = await req.json()
  if (!plotId || !wallet) return NextResponse.json({ error: 'Missing fields' }, { status: 400 })

  const db = supabaseAdmin()

  // Fetch plot
  const { data: plot, error: plotErr } = await db.from('plots').select('*').eq('id', plotId).single()
  if (plotErr || !plot) return NextResponse.json({ error: 'Plot not found' }, { status: 404 })
  if (plot.owner_wallet) return NextResponse.json({ error: 'Plot already claimed' }, { status: 400 })

  const cfg = PLOT_TIERS[plot.tier as PlotTier]

  // Check token balance (skipped in dev bypass mode)
  if (process.env.DEV_BYPASS_BALANCE !== 'true') {
    const balance = await getTokenBalance(wallet)
    if (balance < cfg.claimCost) {
      return NextResponse.json(
        { error: `Insufficient balance. Need ${cfg.claimCost.toLocaleString()} USDC, you have ${balance.toFixed(2)}` },
        { status: 400 },
      )
    }
  }

  // Check player doesn't already own too many plots (optional limit: 5 per wallet for now)
  const { count } = await db.from('plots').select('*', { count: 'exact', head: true }).eq('owner_wallet', wallet)
  if ((count ?? 0) >= 5) {
    return NextResponse.json({ error: 'Max 5 plots per wallet for now' }, { status: 400 })
  }

  // Upsert player FIRST (plots.owner_wallet has FK → players.wallet)
  await db.from('players').upsert({ wallet, updated_at: new Date().toISOString() }, { onConflict: 'wallet' })

  // Claim plot
  const { data: updated, error: updateErr } = await db
    .from('plots')
    .update({ owner_wallet: wallet, locked_tokens: cfg.claimCost, claimed_at: new Date().toISOString() })
    .eq('id', plotId)
    .select()
    .single()

  if (updateErr) return NextResponse.json({ error: updateErr.message }, { status: 500 })

  // Seed any bonus animals from the plot's JSON sidecar (generated by the plot generator)
  try {
    const padded   = String(plotId).padStart(3, '0')
    const sidecar  = JSON.parse(
      await readFile(join(process.cwd(), 'public', 'plots', `plot-${padded}.json`), 'utf8'),
    )
    const bonusAnimals: string[] = sidecar.animals ?? []
    if (bonusAnimals.length > 0) {
      const now = new Date()
      const animalRows = bonusAnimals
        .filter(a => a in ANIMALS)
        .map(a => {
          const ac = ANIMALS[a as keyof typeof ANIMALS]
          return {
            plot_id:      plotId,
            animal_type:  a,
            purchased_at: now.toISOString(),
            next_harvest: new Date(now.getTime() + ac.harvestMs).toISOString(),
          }
        })
      if (animalRows.length > 0) await db.from('animals').insert(animalRows)
    }
  } catch {
    // sidecar missing or malformed — no bonus animals, that's fine
  }

  // Log event + check achievements
  await logEvent('claim', plotId, wallet, { tier: plot.tier })
  const newAchievements = await checkAchievements(wallet, {
    action:   'claim',
    plotTier: plot.tier,
  })

  return NextResponse.json({ plot: updated, newAchievements })
}
